pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'ngcloud/creator:$(build.buildId)'

steps:
- script: docker build -f Dockerfile -t $(imageName) .
  displayName: 'docker build'
- script: |
    docker login -u $(dockerId) -p $(dockerPassword)
    docker push $(imageName)
  displayName: 'docker push'
