pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'ngcloud/creator:$(build.buildId)'

steps:
- script: docker build --build-arg aquaToken=$(aquaToken) -f Dockerfile -t $(imageName) --no-cache .
  displayName: 'docker build'
- script: |
    docker login -u $(dockerId) -p $(dockerPassword)
    docker push $(imageName)
  displayName: 'docker push'
