
variables:
  toolsVersion: '1.0.0'
  coreImageName: 'ngcloud/cloud-tools'
  awsImageName: 'ngcloud/aws-tools'
  azureImageName: 'ngcloud/azure-tools'
  awsCreatorName: 'ngcloud/creator'
  azureCreatorName: 'ngcloud/azure-creator'

pr:
- master
- release/*
- epic/*

trigger:
  batch: true
  branches:
    include:
    - master
    - feature/*
    - epic/*
    - release/*
    exclude:
    - test/*
    - temp/*

jobs:
- job: BuildCore
  displayName: 'Build core tools'
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:  
  - script: docker build --build-arg aquaToken=$(aquaToken) --build-arg CLI_VERSION=$(toolsVersion) --build-arg BUILD_DATE="$(date '+%d/%m/%Y %H:%M:%S')" -f Dockerfile-tools -t $(coreImageName) --no-cache .
    displayName: 'NgCloud core tools docker build'
  - script: |
      docker login -u $(dockerId) -p $pswd
      docker push $(coreImageName)
    displayName: 'Push docker containers for core cloud tools'
    env:
      pswd: $(dockerPassword)
    condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'master'))  

- job: BuildAWS
  dependsOn: BuildCore
  displayName: 'Build aws tools'
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - script: docker build --build-arg aquaToken=$(aquaToken) --build-arg CLI_VERSION=$(toolsVersion) --build-arg BUILD_DATE="$(date '+%d/%m/%Y %H:%M:%S')" -f Dockerfile-aws -t $(awsImageName) --no-cache .
    displayName: 'NgCloud aws tools docker build'
  - script: docker build --build-arg CLI_VERSION=$(toolsVersion) --build-arg BUILD_DATE="$(date '+%d/%m/%Y %H:%M:%S')" -f Dockerfile -t $(awsCreatorName) --no-cache .
    displayName: 'NgCloud Creator docker build (AWS)'
  - script: |
      docker login -u $(dockerId) -p $pswd
      docker push $(awsImageName)
      docker push $(awsCreatorName)
    displayName: 'Push docker containers for aws creator'
    env:
      pswd: $(dockerPassword)
    condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'master')) 

- job: BuildAzure
  dependsOn: BuildCore
  displayName: 'Build azure tools'
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - script: docker build --build-arg aquaToken=$(aquaToken) --build-arg CLI_VERSION=$(toolsVersion) --build-arg BUILD_DATE="$(date '+%d/%m/%Y %H:%M:%S')" -f Dockerfile-azure -t $(azureImageName) --no-cache .
    displayName: 'NgCloud azure tools docker build'
  - script: docker build --build-arg CLI_VERSION=$(toolsVersion) --build-arg BUILD_DATE="$(date '+%d/%m/%Y %H:%M:%S')" -f Dockerfile-azcreator -t $(azureCreatorName) --no-cache .
    displayName: 'NgCloud Creator docker build (Azure)'  
  - script: |
      docker login -u $(dockerId) -p $pswd
      docker push $(azureImageName)
      docker push $(azureCreatorName)  
    displayName: 'Push docker containers for azure creator'
    env:
      pswd: $(dockerPassword)
    condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'master'))
