pool:
  vmImage: 'Ubuntu 16.04'

variables:
  coreImageName: 'ngcloud/cloud-tools'
  imageName: 'ngcloud/creator'

steps:
- script: docker build --build-arg aquaToken=$(aquaToken) -f Dockerfile-tools -t $(coreImageName) --no-cache .
  displayName: 'NgCloud cloud tools docker build'
- script: docker build -f Dockerfile -t $(imageName) --no-cache .
  displayName: 'NgCloud Creator docker build'
- script: |
    docker login -u $(dockerId) -p $pswd
    docker push $(coreImageName)
    docker push $(imageName)
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  env:
    pswd: $(dockerPassword)  
  displayName: 'Push docker containers'
