steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '--build-arg',
         'CLI_VERSION=${_TOOLS_VERSION}',
         '--build-arg',
         'BUILD_DATE=$COMMIT_SHA',
         '-f',
         'Dockerfile-tools',
         '-t',
         'gcr.io/$PROJECT_ID/${_CORE_IMAGE_NAME}',
         '.']
  id: 'build-core'

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker build --build-arg CLI_VERSION=${_TOOLS_VERSION} --build-arg BUILD_DATE=$COMMIT_SHA --build-arg aquaToken=${_AQUA_TOKEN} -f Dockerfile-aws -t gcr.io/$PROJECT_ID/${_AWS_IMAGE_NAME} .']
  id: 'build-aws'
  waitFor:
    - 'build-core'

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker build --build-arg CLI_VERSION=${_TOOLS_VERSION} --build-arg BUILD_DATE=$COMMIT_SHA --build-arg aquaToken=${_AQUA_TOKEN} -f Dockerfile-azure -t gcr.io/$PROJECT_ID/${_AZURE_IMAGE_NAME} .']
  id: 'build-azure'
  waitFor:
    - 'build-core'

- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '--build-arg',
         'CLI_VERSION=${_TOOLS_VERSION}',
         '--build-arg',
         'BUILD_DATE=$COMMIT_SHA',
         '-f',
         'Dockerfile',
         '-t',
         'gcr.io/$PROJECT_ID/${_AWS_CREATOR_NAME}',
         '.']
  id: 'build-awscreator'
  waitFor:
    - 'build-aws'

- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '--build-arg',
         'CLI_VERSION=${_TOOLS_VERSION}',
         '--build-arg',
         'BUILD_DATE=$COMMIT_SHA',
         '-f',
         'Dockerfile-azcreator',
         '-t',
         'gcr.io/$PROJECT_ID/${_AZURE_CREATOR_NAME}',
         '.']
  id: 'build-azurecreator'
  waitFor:
    - 'build-azure'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push',
    'gcr.io/$PROJECT_ID/${_AWS_CREATOR_NAME}'
  ]
  id: 'push-aws-creator'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push',
    'gcr.io/$PROJECT_ID/${_AZURE_CREATOR_NAME}'
  ]
  id: 'push-azure-creator'

substitutions:
  _TOOLS_VERSION: '1.0.0'
  _CORE_IMAGE_NAME: 'ngcloud/cloud-tools'
  _AWS_IMAGE_NAME: 'ngcloud/aws-tools'
  _AZURE_IMAGE_NAME: 'ngcloud/azure-tools'
  _AWS_CREATOR_NAME: 'ngcloud/creator'
  _AZURE_CREATOR_NAME: 'ngcloud/azure-creator'
  _AQUA_TOKEN: ''
images: [
  'gcr.io/$PROJECT_ID/${_CORE_IMAGE_NAME}',
  'gcr.io/$PROJECT_ID/${_AWS_IMAGE_NAME}',
  'gcr.io/$PROJECT_ID/${_AZURE_IMAGE_NAME}',
  'gcr.io/$PROJECT_ID/${_AWS_CREATOR_NAME}',
  'gcr.io/$PROJECT_ID/${_AZURE_CREATOR_NAME}',
]