FROM ngcloud/cloud-tools

ARG CLI_VERSION
ARG BUILD_DATE
ARG aquaToken

LABEL maintainer="ngCloud" \
      org.label-schema.schema-version="1.0" \
      org.label-schema.vendor="ngCloud" \
      org.label-schema.name="cloud tools" \
      org.label-schema.version=$CLI_VERSION \
      org.label-schema.license="MIT" \
      org.label-schema.description="Container with essential tools for creating and managing Kubernetes cluster on aws using kops" \
      org.label-schema.url="https://ngcloud.io" \
      org.label-schema.usage="https://github.com/ngcloud/bootstrap" \
      org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.vcs-url="https://github.com/ngcloud/bootstrap.git" \
      org.label-schema.docker.cmd="docker run -it --name ngcloud-creator -v ~/.aws:/home/ngcloud/.aws -v ~/.ssh:/home/ngcloud/.ssh ngcloud/creator"

ENV AWS_IAM_AUTH_VERSION=0.3.0

# Install kops
RUN curl -LO https://github.com/kubernetes/kops/releases/download/$(curl -s https://api.github.com/repos/kubernetes/kops/releases/latest | grep tag_name | cut -d '"' -f 4)/kops-linux-amd64 \
  && chmod +x kops-linux-amd64 \
  && mv kops-linux-amd64 /usr/local/bin/kops

# Install aws iam authenticator
RUN curl -LO https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/download/v${AWS_IAM_AUTH_VERSION}/heptio-authenticator-aws_${AWS_IAM_AUTH_VERSION}_linux_amd64 \
  && chmod +x heptio-authenticator-aws_${AWS_IAM_AUTH_VERSION}_linux_amd64 \
  && mv ./heptio-authenticator-aws_${AWS_IAM_AUTH_VERSION}_linux_amd64 /usr/local/bin/aws-iam-authenticator

# Install awscli
RUN pip3 install --upgrade pip \
  && pip3 install awscli aws-shell

# Scan with aqua
RUN curl "https://get.aquasec.com/microscanner" -o "/usr/local/bin/microscanner" \
  && chmod +x /usr/local/bin/microscanner \
  && /usr/local/bin/microscanner $aquaToken \
  && rm -rf /usr/local/bin/microscanner
