FROM ngcloud/cloud-tools
LABEL author="Team ngcloud <hello@ngcloud.io>"

ARG CLI_VERSION
ARG BUILD_DATE
ARG aquaToken

LABEL maintainer="ngCloud" \
      org.label-schema.schema-version="1.0" \
      org.label-schema.vendor="ngCloud" \
      org.label-schema.name="azure tools" \
      org.label-schema.version=$CLI_VERSION \
      org.label-schema.license="MIT" \
      org.label-schema.description="Container with essential tools for creating and managing Kubernetes cluster on azure" \
      org.label-schema.url="https://ngcloud.io" \
      org.label-schema.usage="https://github.com/ngcloud/bootstrap" \
      org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.vcs-url="https://github.com/ngcloud/bootstrap.git" \
      org.label-schema.docker.cmd="docker run -it --name ngcloud-creator -v ~/.azure:/home/ngcloud/.azure ngcloud/azure-creator"

ENV ACS_VERSION=0.25.3

# Install azure cli
RUN apk add --virtual=build gcc libffi-dev musl-dev openssl-dev python3-dev make \
  && pip3 install azure-cli \
  && apk del --purge build

# Install acs-engine
RUN curl -LO https://github.com/Azure/acs-engine/releases/download/v${ACS_VERSION}/acs-engine-v${ACS_VERSION}-linux-amd64.zip \
  && unzip acs-engine-v${ACS_VERSION}-linux-amd64.zip -d /usr/local/bin \
  && mv /usr/local/bin/acs-engine-v${ACS_VERSION}-linux-amd64/acs-engine /usr/local/bin/acs-engine \
  && chmod +x /usr/local/bin/acs-engine \
  && rm acs-engine-v${ACS_VERSION}-linux-amd64.zip

# Scan with aqua
RUN curl "https://get.aquasec.com/microscanner" -o "/usr/local/bin/microscanner" \
  && chmod +x /usr/local/bin/microscanner \
  && /usr/local/bin/microscanner $aquaToken \
  && rm -rf /usr/local/bin/microscanner
