FROM alpine

ARG CLI_VERSION
ARG BUILD_DATE

LABEL maintainer="ngCloud" \
      org.label-schema.schema-version="1.0" \
      org.label-schema.vendor="ngCloud" \
      org.label-schema.name="cloud tools" \
      org.label-schema.version=$CLI_VERSION \
      org.label-schema.license="MIT" \
      org.label-schema.description="Container with essential tools for managing Kubernetes cluster" \
      org.label-schema.url="https://ngcloud.io" \
      org.label-schema.usage="https://github.com/ngcloud/bootstrap" \
      org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.vcs-url="https://github.com/ngcloud/bootstrap.git" \
      org.label-schema.docker.cmd=""

ENV TF_VERSION=0.11.10

RUN apk --update add --no-cache python3 py3-pip zip tar make bash wget curl jq git openssl openssh-client \
    && rm -rf /var/lib/apt/lists/*
RUN apk add --no-cache ca-certificates && update-ca-certificates

# Setup kubectl
RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl \
  && chmod +x ./kubectl \
  && mv ./kubectl /usr/local/bin/kubectl

# Install helm
RUN mkdir -p /usr/share/helm && curl https://raw.githubusercontent.com/helm/helm/master/scripts/get | bash \
  && chmod +x /usr/local/bin/helm \
  && chmod +x /usr/local/bin/tiller \
  && helm init --client-only \
  && helm plugin install https://github.com/hypnoglow/helm-s3.git

# Install terraform
RUN curl -LO https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip \
  && unzip terraform_${TF_VERSION}_linux_amd64.zip -d /usr/local/bin \
  && chmod +x /usr/local/bin/terraform \
  && rm terraform_${TF_VERSION}_linux_amd64.zip

