apiVersion: v1
kind: Pod
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  creationTimestamp: null
  labels:
    k8s-app: etcd-manager-main
  name: etcd-manager-main
  namespace: kube-system
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - mkfifo /tmp/pipe; (tee -a /var/log/etcd.log < /tmp/pipe & ) ; exec /etcd-manager
      --backup-store=s3://dev-ngcloud-bucket/dev1.k8s.local/backups/etcd/main --client-urls=http://__name__:4001
      --cluster-name=etcd --containerized=true --dns-suffix=internal.dev1.k8s.local
      --grpc-port=3996 --peer-urls=http://__name__:2380 --quarantine-client-urls=http://__name__:3994
      --v=8 --volume-name-tag=k8s.io/etcd/main --volume-provider=aws --volume-tag=k8s.io/etcd/main
      --volume-tag=k8s.io/role/master=1 --volume-tag=kubernetes.io/cluster/dev1.k8s.local=owned
      > /tmp/pipe 2>&1
    image: kopeio/etcd-manager:1.0.20181001
    name: etcd-manager
    resources:
      requests:
        cpu: 200m
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /rootfs
      name: rootfs
    - mountPath: /etc/hosts
      name: hosts
    - mountPath: /var/log/etcd.log
      name: varlogetcd
  hostNetwork: true
  tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  volumes:
  - hostPath:
      path: /
      type: Directory
    name: rootfs
  - hostPath:
      path: /etc/hosts
      type: File
    name: hosts
  - hostPath:
      path: /var/log/etcd.log
      type: FileOrCreate
    name: varlogetcd
status: {}
